# This is the production variant of
# docker deployment for {{app_name}}
version: '3'
services:

  # development instance
  app-development:
    image: index.docker.io/forthgreen/backend:beta
    container_name: 'app-development'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=beta
      - MONGO_HOST=database
      - MONGO_DB=forthgreen-beta
      - HOST=http://52.14.88.170/beta/api/
      - RABBITMQ_HOST=cat.rmq.cloudamqp.com
      - RABBITMQ_USER=cmyqzbid
      - RABBITMQ_PASSWORD=9gVvbEESmcHgTyb4sBD2kiuZKcWMlu6i
      - RABBITMQ_HEARTBEAT=259200
    env_file:
      - .env

  admin:
    image: index.docker.io/forthgreen/adminpanel:beta
    container_name: 'admin'
    ports:
      - 8002:8002
    environment:
      - NODE_ENV=development
      - URL=http://52.14.88.170/beta/api/

  app-admin:
    image: index.docker.io/forthgreen/admin:beta
    container_name: 'app-admin'
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=development
      - URL=http://52.14.88.170/beta/api/

  # nginx for port forwarding and proxy server
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    depends_on:
      - app-development
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx-beta.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/nginx/certs