# This is the production variant of
# docker deployment for {{app_name}}
version: '3'
services:

  # development instance
  app-development:
    image: index.docker.io/forthgreen/backend:staging
    container_name: 'app-development'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=staging
      - MONGO_HOST=database
      - MONGO_DB=forthgreen-staging
      - HOST=https://profile.forthgreen.com/staging/api/
      - RABBITMQ_HOST=cat.rmq.cloudamqp.com
      - RABBITMQ_USER=cmyqzbid
      - RABBITMQ_PASSWORD=9gVvbEESmcHgTyb4sBD2kiuZKcWMlu6i
      - RABBITMQ_HEARTBEAT=259200
      - WEBAPP_URL=https://profile.forthgreen.com/staging/api/
      - NEW_BUSINESS_ALERT_EMAIL=santi.gomez@forthgreen.com
      - BUSINESS_EMAIL=register@forthgreen.com
      - BUSINESS_EMAIL_PASSWORD=kzqmhocfchvsuort
      - SECRET_STRING=H7gGu8s9shdJH
      
    env_file:
      - .env
    command: "pm2-docker server/loader.js --machine-name forthgreen"

  admin:
    image: index.docker.io/forthgreen/adminpanel:staging
    container_name: 'admin'
    ports:
      - 8002:8002
    environment:
      - NODE_ENV=development
      - URL=https://profile.forthgreen.com/staging/api/

  app-admin:
    image: index.docker.io/forthgreen/admin:staging
    container_name: 'app-admin'
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=development
      - URL=http://3.23.147.117/staging/api/

  # nginx for port forwarding and proxy server
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    depends_on:
      - app-development
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx-staging.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/nginx/certs