# This is the production variant of
# docker deployment for {{app_name}}
version: '3'
services:

  # development instance
  app:
    image: index.docker.io/forthgreen/backend:master
    container_name: 'app'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - MONGO_HOST=database
      - MONGO_DB=forthgreen
      - RABBITMQ_HOST=baboon-01.rmq.cloudamqp.com
      - RABBITMQ_USER=dbmphhlg
      - RABBITMQ_PASSWORD=LmrORQxFunc9RD5C0fVuIRS-2HGD_LMe
      - RABBITMQ_HEARTBEAT=259200
      - HOST=http://localhost:3000/api/
      - WEBAPP_URL=http://localhost:3000/api/

    env_file:
      - .env
    command: bash -c "node server/loader.js"
  admin:
    image: index.docker.io/forthgreen/adminpanel:master
    container_name: 'admin'
    ports:
      - 8002:8002
    environment:
      - NODE_ENV=development
      - URL=http://3.22.243.209/production/api/
  
  app-admin:
    image: index.docker.io/forthgreen/admin:master
    container_name: 'app-admin'
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=development
      - URL=http://3.22.243.209/production/api/

  # nginx for port forwarding and proxy server
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/nginx/certs

  watchtower:
    image: v2tec/watchtower
    container_name: 'watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config.json:/config.json
    command: --interval 10 --cleanup
